# Netlify 部署配置
[build]
  publish = "."
  
[[redirects]]
  from = "/"
  to = "/landing-page.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    # 启用压缩
    Content-Encoding = "gzip"
    # 缓存控制
    Cache-Control = "public, max-age=31536000"
    # 安全头
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

